name: Publish new Release

on:
  release:
    types: [published]
    branches: [main]

jobs:
  release:
    uses: evolution-gaming/scala-github-actions/.github/workflows/release.yml@7b1a7e5670072b17562e41c014900233bd640c1c
    secrets: inherit
